language: node_js
node_js: "node"
cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

install:
  - npm install
  - npm run build

script:
  - echo 'Build done :)' # 'docs.wasabiwallet.io' > docs/.vuepress/dist/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  keep_history: true
  local_dir: docs/.vuepress/dist
  on:
    branch: master
