# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
- task: CacheBeta@0
  inputs:
    key: $(Build.SourcesDirectory)/package-lock.json
    path: $(npm_config_cache)
  displayName: Cache npm
- script: |
    # install dependencies
    npm ci
    npm run build
    # navigate into the build output directory
    cd docs/.vuepress/dist
    echo 'docs.wasabiwallet.io' > CNAME
    # git setup
    git init
    git config user.email "azure-pipeline@wasabiwallet.io"
    git config user.name "Azure Pipeline"
    git remote add origin https://lontivero:$(GITHUB_DEPLOY_ACCESS_TOKEN)@github.com/zkSNACKs/WasabiDoc.git
    # add and push build
    git add -A
    git commit -m 'deploy'
    git push -f origin master:gh-pages
  displayName: 'Build and Deploy'
