# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
- task: CacheBeta@0
  inputs:
    key: $(Build.SourcesDirectory)/package-lock.json
    path: $(npm_config_cache)
  displayName: Cache npm
- script: |
    git config --global user.email "azure-pipeline@wasabiwallet.io"
    git config --global user.name "Azure Pipeline"
    npm ci
  displayName: 'Setup'
- script: |
    export REPO_URL=https://$GITHUB_DEPLOY_ACCESS_TOKEN@github.com/zkSNACKs/WasabiDoc.git
    npm run deploy
  displayName: 'Build and Deploy'
